services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: game
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U game -d game" ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build: ./services/api
    profiles: [ "prod" ]
    env_file:
      - ./services/api/.env
      - ./services/api/.env.local
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./services/worker
    profiles: [ "prod" ]
    env_file:
      - ./services/worker/.env
      - ./services/worker/.env.local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./services/frontend
    profiles: [ "prod" ]
    env_file:
      - ./services/frontend/.env
      - ./services/frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started

  bot:
    build: ./services/bot
    profiles: [ "prod" ]
    env_file:
      #- ./services/bot/.env
      - ./services/bot/.env.local
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_started

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_started

  # Development profile: hot-reload API and worker using ts-node-dev
  api-dev:
    profiles: [ "dev" ]
    image: node:20-bookworm-slim
    working_dir: /app
    command: sh -c "npm install && npx prisma generate && npx prisma db push && npm run dev"
    environment:
      NODE_ENV: development
      # Use a separate Prisma schema for dev to isolate tables
      DATABASE_URL: postgresql://game:gamepass@postgres:5432/game?schema=dev
    env_file:
      - ./services/api/.env
      - ./services/api/.env.local
    volumes:
      - ./services/api:/app
      # keep container node_modules so host mount doesn't hide it
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker-dev:
    profiles: [ "dev" ]
    image: node:20-bookworm-slim
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      # Match API dev DB schema for isolation
      DATABASE_URL: postgresql://game:gamepass@postgres:5432/game?schema=dev
    env_file:
      - ./services/worker/.env
      - ./services/worker/.env.local
    volumes:
      - ./services/worker:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend-dev:
    profiles: [ "dev" ]
    image: node:20-bookworm-slim
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
    env_file:
      - ./services/frontend/.env
      - ./services/frontend/.env.local
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      api-dev:
        condition: service_started

  bot-dev:
    profiles: [ "dev" ]
    image: node:20-bookworm-slim
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
    env_file:
      # - ./services/bot/.env
      - ./services/bot/.env.local
    volumes:
      - ./services/bot:/app
      - /app/node_modules
    depends_on:
      api-dev:
        condition: service_started
      redis:
        condition: service_started

volumes:
  db-data:
  redis-data:
